bundle
QuasiStellar/shattered-pixel-dungeon-remastered pull request #12
Opened 2022-08-21 00:35 UTC by Zrp200

2022-08-21 17:50 UTC, QuasiStellar requested changes

2022-08-21 17:50 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/utils/Bundle.kt
> +                    .forEachLine { append(it + "\n") }
formatting

2022-08-21 17:50 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/utils/Bundle.kt
> +    private inline fun <R,RArray> getArray(
formatting

2022-08-21 21:36 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/utils/Bundle.kt
> +    private inline fun <R,RArray> getArray(
exactly what's wrong here? all of the parameters are on separate lines this time.

2022-08-21 21:41 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/utils/Bundle.kt
> +    private inline fun <R,RArray> getArray(
Space between type arguments (just use ctrl+alt+L)

2022-08-22 20:34 UTC, QuasiStellar approved these changes

2022-08-22 20:34 UTC, merged