barray
QuasiStellar/shattered-pixel-dungeon-remastered pull request #14
Opened 2022-08-26 00:55 UTC by Zrp200

2022-08-26 18:53 UTC, QuasiStellar requested changes

2022-08-26 18:53 UTC, QuasiStellar commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +    result ?: return BooleanArray(size) { predicate(get(it)) }
```kotlin
private inline fun IntArray.mapInto(
    result: BooleanArray?,
    predicate: (Int) -> Boolean
): BooleanArray = result?.also { repeat(size) { result[it] = predicate(get(it)) } }
    ?: BooleanArray(size) { predicate(get(it)) }

2022-08-26 18:53 UTC, QuasiStellar commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +fun BooleanArray.not(result: BooleanArray?) = mapInto(result, Boolean::not)
`result` is always null in use cases, should have null as the default here and everywhere else, I think

2022-08-26 18:53 UTC, QuasiStellar commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +fun BooleanArray.and(b: BooleanArray, result: BooleanArray?): BooleanArray {
linebreak

2022-08-26 18:53 UTC, QuasiStellar commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +    if (!::falseArray.isInitialized || falseArray.size < size) falseArray = BooleanArray(size)
What's the point in it being lateinit?

2022-08-27 23:12 UTC, Zrp200 commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +    if (!::falseArray.isInitialized || falseArray.size < size) falseArray = BooleanArray(size)
It's never null.

2022-08-27 23:13 UTC, Zrp200 commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +    if (!::falseArray.isInitialized || falseArray.size < size) falseArray = BooleanArray(size)
Now that I think of it, it could just be assigned an empty array to start.

2022-08-27 23:18 UTC, Zrp200 commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +fun BooleanArray.not(result: BooleanArray?) = mapInto(result, Boolean::not)
null is the default. It's an overload. it just so happens that the default overload also matches an operator.

2022-08-27 23:20 UTC, Zrp200 commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +fun BooleanArray.not(result: BooleanArray?) = mapInto(result, Boolean::not)
For whatever reason evan made that decision to define the method to take another boolean array, I'm not going to be the one to declare that doing such is pointless.

2022-08-27 23:23 UTC, Zrp200 commented on core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/utils/BArray.kt
> +    result ?: return BooleanArray(size) { predicate(get(it)) }
this is no longer applicable.

2022-08-29 19:13 UTC, QuasiStellar approved these changes

2022-08-29 19:14 UTC, merged