Ported watabou.noosa.audio to kotlin
QuasiStellar/shattered-pixel-dungeon-remastered pull request #9
Opened 2022-08-18 23:38 UTC by Zrp200

2022-08-19 09:01 UTC, QuasiStellar requested changes
Rename the commit "remaster: ..." to keep the consistency.
I will make a PR template sometime soon.

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    fun play(assetName: String?, looping: Boolean) {
assetName can't be null

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    private val trackQueue = ArrayList<String?>()
Strings inside trackQueue can't be null

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +import java.util.*
don't use wildcard imports

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        @JvmName("volume") get
redundant getter

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    @JvmField var trackList: Array<String>? = null
can be private

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    lateinit var trackChances: FloatArray
can be private

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        if (trackList?.isEmpty() != false || music !== player || player!!.isLooping) {
!= false?

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    lateinit var trackChances: FloatArray
trackList and trackChances can be one map

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        if (!isEnabled || trackQueue.isEmpty()) {
already checked for isEmpty

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        player = null // this deactives the volume setter logic.
why is this needed?

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    val isPlaying get() = player?.isPlaying == true
== true?

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        kotlin.runCatching {
kotlin is redundant

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +                isLooping = this@MusicPlayer.looping
this@MusicPlayer is redundant

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +object Sample {
can be renamed to SamplePlayer

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +    private data class DelayedSoundEffect(var id: Any? = null,
styleguide:
```
private data class DelayedSoundEffect(
    var id: Any? = null,
    var delay: Float = 0f,
    var leftVol: Float = 0f,
    var rightVol: Float = 0f,
    var pitch: Float = 0f
)

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    fun pause() { player?.pause() }
block-like methods should always have linebreaks

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    @JvmField var trackList: Array<String>? = null
var annotations should be on their own lines

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        var assetName = assetName
name shadowed

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        if (tracks == null || tracks.isEmpty() || tracks.size != chances.size) {
can be replaced with isNullOrEmpty()

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +            player = Gdx.audio.newMusic(Gdx.files.internal(track)).apply {
There is a function for getting internal files: getAsset

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +                    synchronized(this@Sample) { ids[asset] = newSound }
getAsset

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +    private var ids = HashMap<Any?, Sound>()
should be String instead of Any?

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +    fun pause() { ids.values.forEach(Sound::pause) }
linebreaks

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +    fun unload(src: Any?) { ids.remove(src)?.dispose() }
src is String

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +    fun play(id: Any?, leftVolume: Float, rightVolume: Float, pitch: Float): Long {
id is String

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +import com.watabou.noosa.audio.Sample
unused imports

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +        synchronized(delayedSFX) { delayedSFX.add(DelayedSoundEffect(
formatting

2022-08-19 09:01 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +    fun playDelayed(id: Any?, delay: Float, volume: Float = 1f, pitch: Float = 1f) = playDelayed(id, delay, volume, volume, pitch)
id is String

2022-08-19 15:08 UTC, Zrp200 commented
Will fix these later today.

2022-08-20 18:01 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        if (trackList?.isEmpty() != false || music !== player || player!!.isLooping) {
if it is null or true.

2022-08-20 18:05 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        if (!isEnabled || trackQueue.isEmpty()) {
this was present in the original code. I'll fix it now though.

2022-08-20 18:07 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        player = null // this deactives the volume setter logic.
what is 'this'

2022-08-20 18:09 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    val isPlaying get() = player?.isPlaying == true
original code returned false if it was null.

2022-08-20 18:10 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        kotlin.runCatching {
it's a different method. I didn't need `this` to be bound.

2022-08-20 18:11 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        kotlin.runCatching {
I'll fix it anyway, but it's redundant.

2022-08-20 18:11 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        player = null // this deactives the volume setter logic.
Deactivating volume setter logic

2022-08-20 18:12 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +                isLooping = this@MusicPlayer.looping
okay, if you say so. Figured it would be nice for consistency.

2022-08-20 18:12 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +object Sample {
I'm not in the mood to rename all uses. You can do it if you like.

2022-08-20 18:14 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +                isLooping = this@MusicPlayer.looping
Makes sense, better leave it then

2022-08-20 18:16 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    @JvmField var trackList: Array<String>? = null
okay. I'll put it how you like it.

2022-08-20 18:18 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        if (tracks == null || tracks.isEmpty() || tracks.size != chances.size) {
oh, huh, didn't know that one existed.

2022-08-20 18:22 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    val isPlaying get() = player?.isPlaying == true
Ah, right

2022-08-20 18:23 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +object Sample {
Isn't it automatic?

2022-08-20 18:24 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    @JvmField var trackList: Array<String>? = null
That's not me,  that's standard Kotlin linter

2022-08-20 20:03 UTC, Zrp200 commented
It currently appears to not entirely work, hold on while I look into it.

2022-08-20 21:17 UTC, Zrp200 commented
okay it should be fixed now

2022-08-20 21:26 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +        player = null // this deactives the volume setter logic.
done

2022-08-20 21:27 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +object Sample {
maybe but it makes the pull request larger for little reason.

2022-08-20 21:27 UTC, Zrp200 commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +import java.util.*
fixed

2022-08-22 20:30 UTC, QuasiStellar approved these changes

2022-08-22 20:30 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/MusicPlayer.kt
> +    private var trackMap: Map<String,Float> = emptyMap()
Space after the comma
![image](https://user-images.githubusercontent.com/30569097/185769638-d5a2e748-ee70-43bb-93fc-651ecadd1998.png)

2022-08-22 20:30 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +object Sample {
Well, that's not a problem

2022-08-22 20:30 UTC, QuasiStellar commented on SPD-classes/src/main/java/com/watabou/noosa/audio/Sample.kt
> +        for(sound in ids.values) sound.dispose()
Space after for, reformat the code before commiting

2022-08-22 20:32 UTC, merged